{% set version = "6.10.1" %}
package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: abbca7ed381d34a77699c6cb68be67919a1e7f5cf8728b57396145417fa34110

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django

about:
    home: https://testfixtures.readthedocs.io
    license: MIT
    license_file: LICENSE.txt
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
    doc_url: https://testfixtures.readthedocs.io
    dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
   
