{% set version = "6.10.2" %}
package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: c0eb9d20ce3b53e0cf543da7c46c263cc9792f13223def8b26edb6180ecdc895

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django

about:
    home: https://testfixtures.readthedocs.io
    license: MIT
    license_file: LICENSE.txt
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
    doc_url: https://testfixtures.readthedocs.io
    dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
   
