{% set version = "6.14.2" %}
package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: 14d9907390f5f9c7189b3d511b64f34f1072d07cc13b604a57e1bb79029376e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django

about:
  home: https://testfixtures.readthedocs.io
  license: MIT
  license_file: LICENSE.txt
  summary: A collection of helpers and mock objects for unit tests and doc tests.
  doc_url: https://testfixtures.readthedocs.io
  dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
