{% set version = "9.0.0" %}
{% set python_min = "3.11.0" %}
package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: a858e7fd665e5039d6d86c7951d9a231008e18e993ea8624cb20bbec6d49fed4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    python {{ python_min }}
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django

about:
  home: https://testfixtures.readthedocs.io
  license: MIT
  license_file: LICENSE.txt
  summary: A collection of helpers and mock objects for unit tests and doc tests.
  doc_url: https://testfixtures.readthedocs.io
  dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
